server {
    listen 80;
    server_name localhost;
    autoindex off;

    location / {
        add_header X-Robots-Tag "noindex, nofollow" always;
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /health {
        allow 127.0.0.1;         # localhost only       
        deny all;
        access_log off;

        return 200 'OK';
        add_header Content-Type application/json;
    }
}
